server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/files/{application}/{profile}
  profiles:
    active: native

  mvc:
    media-types:
      bin: application/octet-stream